version: "3.9"
networks:
  default:
    driver:  bridge

services:
  php-apache:
    container_name: typo3_app
    networks:
      - default
    ports:
      - "8088:80"
    build: './build/php'
    depends_on:
      - mysql
      - chrome
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: "Europe/Sofia"

  mysql:
    container_name: typo3_mysql
    networks:
      - default
    restart: always
    ports:
      - "3309:3306"
    build: './build/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: "typo3_mysql"
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "typo3_database"
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: typo3_phpmyadmin
    networks:
      - default
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysql

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: typo3_chrome
    networks:
      - default
    ports:
      - "4444:4444"

  webgrind:
    image: jokkedk/webgrind:latest
    platform: linux/amd64
    container_name: typo3_webgrind
    #networks:
    #  - default
    ports:
      - "8086:80"
    volumes:
      - ./app/var/cache/xdebug:/tmp

volumes:
  app:
  database: