version: "3.9"
services:
  php-apache:
    container_name: typo3_app
    ports:
      - "80:80"
    build: './build/php'
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: "Europe/Sofia"
  mysql:
    container_name: typo3_mysql
    restart: always
    ports:
      - "3309:3306"
    build: './build/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "typo3_database"
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql
volumes:
  app:
  database: