version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - database:/var/lib/mysql
volumes:
  app:
  database: