services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  #VasilDakov\SitePackage\Domain\Model\Example:
  #  public: true

  #VasilDakov\SitePackage\Domain\Repository\ProductRepository:
  #  public: true

  VasilDakov\SitePackage\:
    resource: '../Classes/*'
    #exclude: '../Classes/Domain/Model/*'